# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"

reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false

  pre_merge_checks:
    docstrings:
      # Disabled: detekt UndocumentedPublicClass/UndocumentedPublicFunction
      # enforces KDoc on all production code. Test functions use descriptive
      # backtick names (idiomatic Kotlin) which this check cannot recognise,
      # causing false failures. Documentation quality is enforced by detekt
      # and CodeRabbit path_instructions instead.
      mode: "off"

  auto_review:
    enabled: true
    drafts: false

  # Exclude generated/binary files from review
  path_filters:
    - "!app/build/**"
    - "!build/**"
    - "!.gradle/**"
    - "!gradle/wrapper/**"
    - "!**/*.webp"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.jpeg"
    - "!**/*.svg"
    - "!**/*.gif"
    - "!**/*.so"
    - "!**/*.jar"
    - "!**/*.aar"
    - "!**/*.apk"
    - "!**/*.aab"
    - "!**/*.keystore"

  path_instructions:
    - path: "**/*.kt"
      instructions: |
        Android Automotive OS (AAOS) project, Kotlin, API 29–36, AGP 9.0.1.
        AGP 9.0.1 manages Kotlin compilation internally — the kotlin-android
        plugin is intentionally not applied.
        Review for: Android lifecycle correctness, AAOS-specific patterns,
        CarUxRestrictions compliance (all game interactions must be gated when
        the vehicle is not in park), proper resource cleanup, and idiomatic
        Kotlin. Flag deprecated API usage.
        Documentation: all public classes and functions must have KDoc. Flag
        missing KDoc on public APIs. Reject trivial comments that restate the
        code (e.g., "// increment counter" above counter++).

    - path: "docs/decisions/**/*.md"
      instructions: |
        ADR format: title, date, status (Proposed/Accepted/Deprecated/Superseded),
        context, decision, consequences. Flag ADRs missing any of these sections
        or with a status of Proposed that has not been actioned.

    - path: "app/src/test/**/*.kt"
      instructions: |
        Unit tests for pure Kotlin game logic (no Android dependencies).
        Uses JUnit 4 and MockK. Review for: coverage of edge cases (win, draw,
        invalid moves), descriptive test names (backtick function names are
        idiomatic Kotlin test style), no @Ignore without an explanation comment,
        no assertions without a failure message in ambiguous cases.
        JaCoCo enforces 80% instruction coverage on game/** — flag tests that
        appear to inflate coverage without testing real behaviour (e.g., tests
        with no assertions, tests that only call constructors).

    - path: "app/src/main/AndroidManifest.xml"
      instructions: |
        This app targets Android Automotive OS for the Play Store for Automotive.
        Verify: android.hardware.type.automotive uses-feature is present and
        required=true, activity flags are appropriate for automotive, no
        permissions or features that would fail Play Store for Automotive review.

    - path: "app/src/main/res/layout*/**/*.xml"
      instructions: |
        Layout targets AAOS automotive_1024p_landscape (1024x600dp), landscape
        only. Review for: interactive touch targets >= 72dp, no small or
        hard-to-tap elements, landscape-first composition. Flag anything that
        would be unusable while wearing driving gloves or on a vehicle display.

    - path: "**/*.gradle.kts"
      instructions: |
        AGP 9.0.1 with Gradle 9.3.1. Flag deprecated configurations or APIs.
        Note: AGP 9.x emits a "incompatible with Gradle 10" deprecation warning
        that is expected and non-blocking — do not flag this.

    - path: ".github/workflows/**/*.yml"
      instructions: |
        CI pipeline: ktlintCheck → detekt → lintDebug → testDebugUnitTest →
        jacocoGameCoverageVerification → assembleDebug. Flag any steps that
        are redundant with the Lefthook pre-commit/pre-push hooks, or any
        missing coverage gaps.

chat:
  auto_reply: true
